version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_sammi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sammi_ecommerce
      MYSQL_USER: sammi
      MYSQL_PASSWORD: 123@123aA
    ports:
      - "8003:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sammi_network

  redis:
    image: redis:latest
    container_name: redis_sammi
    restart: always
    ports:
      - "6379:6379"
    networks:
      - sammi_network

  sammi.ecom.api:
    container_name: sammiecomapi
    image: ${DOCKER_REGISTRY-}sammiecomapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8081
    depends_on:
      - mysql
      - redis
    environment:
      - ConnectionStrings__DefaultConnection=Server=mysql_sammi;Database=sammi_ecommerce;User=root;Password=123456;
    networks:
      - sammi_network

volumes:
  mysql_data:

networks:
  sammi_network: