
services:
  mysql:
    image: mysql:latest
    container_name: mysql_sammi
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: sammi_ecommerce
      MYSQL_USER: sammi
      MYSQL_PASSWORD: 123@123aA
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sammi_network

  # redis:
  #   image: redis:latest
  #   container_name: redis_sammi
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   networks:
  #     - sammi_network

  # elasticsearch:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
  #   container_name: es01
  #   restart: always
  #   environment:
  #   - discovery.type=single-node
  #   - ES_JAVA_OPTS=-Xms512m -Xmx512m
  #   - xpack.security.enabled=false
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   ports:
  #   - "9200:9200"
  #   - "9300:9300"
  #   volumes:
  #   - es_data:/usr/share/elasticsearch/data
  #   networks:
  #   - sammi_network
   
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sammi_api
    restart: always
    depends_on:
      - mysql
      # - redis
      # - elasticsearch
    environment:
      ConnectionStrings__DefaultConnection: "server=mysql_sammi;port=3306;database=sammi_ecommerce;user=root;password=123456"
      # Redis__Connection: "redis:6379"
      # Elastic_Connection: "http://elasticsearch:9200"
    ports:
      - "5000:5000"
      - "5001:5001"
    networks:
      - sammi_network

networks:
  sammi_network:

volumes:
  mysql_data:
  es_data: